# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://drinkw.co
title: Drink W/ Co
email: info@drinkw.co
author: Your Name
description: Drink W/ Co
copyright: 'Copyright &copy; 2015 Your Name. All Rights Reserved.'
credits: ''

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/eventsieco
  - title: facebook
    url: https://facebook.com/eventsieco
  - title: instagram
    url: https://instagram.com/eventsieapp/
